pr: none

jobs:
  - job: "Test"

    strategy:
      matrix:
        linux-stable:
          imageName: 'ubuntu-16.04'
          rustup_toolchain: stable
        linux-beta:
          imageName: 'ubuntu-16.04'
          rustup_toolchain: beta
        linux-nightly:
          imageName: 'ubuntu-16.04'
          rustup_toolchain: nightly

    pool:
      vmImage: $(imageName)

    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: Install Rust

      - script: cargo build --all
        displayName: Cargo build

      - script: cargo test --all
        displayName: Cargo test

  - job: "Clippy"

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: Install Rust

      - script: rustup component add clippy
        displayName: Install Clippy

      - script: cargo clippy --all
        displayName: Run Clippy

  - job: "Rustfmt"

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: Install Rust

      - script: rustup component add rustfmt
        displayName: Install Rustfmt

      - script: cargo fmt --all -- --check
        displayName: Run Rustfmt
