pr: none

resources:
  containers:
    - container: postgres
      image: postgres
      env:
        POSTGRES_USER: venja_test
      ports:
        - 5432:5432

variables:
  cargo_make_run_codecov: true
  database_url: 'postgres://venja_test@postgres/venja_test'
  venja_env: test

jobs:
  - job: "Preview"

    pool:
      vmImage: 'ubuntu-16.04'

    container: rustlang/rust:nightly

    services:
      postgres: postgres

    steps:
      - script: cargo test
        displayName: Run tests

  - job: "Test"

    pool:
      vmImage: 'ubuntu-16.04'

    container: rust:1.34

    services:
      postgres: postgres

    steps:
      - script: apt-get update && apt-get install -y sudo
        displayName: Install sudo

      - script: build/cargo-make.sh
        displayName: Install cargo-make

      - script: cargo make ci-flow
        displayName: Run tests

  - job: "Clippy"

    pool:
      vmImage: 'ubuntu-16.04'

    container: rust:1.34

    steps:
      - script: rustup component add clippy
        displayName: Install Clippy

      - script: cargo clippy --all
        displayName: Run Clippy

  - job: "Rustfmt"

    pool:
      vmImage: 'ubuntu-16.04'

    container: rust:1.34

    steps:
      - script: rustup component add rustfmt
        displayName: Install Rustfmt

      - script: cargo fmt --all -- --check
        displayName: Run Rustfmt
