[tasks.clippy]
command = "cargo"
args = ["clippy", "--all"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.qa]
dependencies = [
    "format",
    "clippy",
    "test"
]
