[tasks.clippy]
command = "cargo"
args = ["clippy", "--all"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.migrate]
command = "diesel"
args = ["migration", "run"]

[tasks.test]
env = { "VENJA_ENV" = "test" }
command = "cargo"
args = ["test"]

[tasks.qa]
dependencies = [
    "format",
    "clippy",
    "test"
]
