version: 2.1

jobs:
  test-stable:
    docker:
      - image: rust:1.34
        environment:
          CARGO_MAKE_RUN_CODECOV: true
          DATABASE_URL: postgres://postgres@localhost/venja_test
          VENJA_ENV: test
      - image: postgres:11.2-alpine
        environment:
          POSTGRES_DB: venja_test

    steps:
      - checkout

      - run:
          name: Install sudo
          command: apt-get update && apt-get install -y sudo

      - run:
          name: Install cargo-make
          command: build/cargo-make.sh

      - run:
          name: Install Diesel
          command: cargo install diesel_cli

      - run:
          name: Migrate database
          command: diesel migration run

      - run:
          name: Run tests
          command: cargo make ci-flow

  test-nightly:
    docker:
      - image: rustlang/rust:nightly
        environment:
          CARGO_MAKE_RUN_CODECOV: true
          DATABASE_URL: postgres://postgres@localhost/venja_test
          VENJA_ENV: test
      - image: postgres:11.2-alpine
        environment:
          POSTGRES_DB: venja_test

    steps:
      - checkout

      - run:
          name: Install Diesel
          command: cargo install diesel_cli

      - run:
          name: Migrate database
          command: diesel migration run

      - run:
          name: Run tests
          command: cargo test

  clippy:
    docker:
      - image: rust:1.34

    steps:
      - checkout

      - run:
          name: Install Clippy
          command: rustup component add clippy

      - run:
          name: Run Clippy
          command: cargo clippy --all

  rustfmt:
    docker:
      - image: rust:1.34

    steps:
      - checkout

      - run:
          name: Install Rustfmt
          command: rustup component add rustfmt

      - run:
          name: Run Rustfmt
          command: cargo fmt --all -- --check

workflows:
  version: 2
  test:
    jobs:
      - clippy
      - rustfmt
      - test-nightly
      - test-stable
