version: 2.1

jobs:
  test-stable:
    docker:
      - image: rust:1.36
        environment:
          DATABASE_URL: postgres://postgres@localhost/venja_test
          VENJA_ENV: test
      - image: postgres:11.2-alpine
        environment:
          POSTGRES_DB: venja_test

    steps:
      - checkout

      - run:
          name: Install Diesel
          command: cargo install diesel_cli

      - run:
          name: Migrate database
          command: diesel migration run

      - run:
          name: Run tests
          command: cargo test

  test-nightly:
    docker:
      - image: rustlang/rust:nightly
        environment:
          DATABASE_URL: postgres://postgres@localhost/venja_test
          VENJA_ENV: test
      - image: postgres:11.2-alpine
        environment:
          POSTGRES_DB: venja_test

    steps:
      - checkout

      - run:
          name: Install Diesel
          command: cargo install diesel_cli

      - run:
          name: Migrate database
          command: diesel migration run

      - run:
          name: Run tests
          command: cargo test

  clippy:
    docker:
      - image: rust:1.36

    steps:
      - checkout

      - run:
          name: Install Clippy
          command: rustup component add clippy

      - run:
          name: Run Clippy
          command: cargo clippy --all

  rustfmt:
    docker:
      - image: rust:1.36

    steps:
      - checkout

      - run:
          name: Install Rustfmt
          command: rustup component add rustfmt

      - run:
          name: Run Rustfmt
          command: cargo fmt --all -- --check

  test-react:
    docker:
      - image: circleci/node:12

    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "app/yarn.lock" }}

      - run:
          name: Install dependencies
          command: cd app && yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "app/yarn.lock" }}
          paths:
            - ./app/node_modules

      - run:
          name: Run tests
          command: cd app && yarn test

  prettier:
    docker:
      - image: circleci/node:12

    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "app/yarn.lock" }}

      - run:
          name: Install dependencies
          command: cd app && yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "app/yarn.lock" }}
          paths:
            - ./app/node_modules

      - run:
          name: Prettier
          command: cd app && ./node_modules/.bin/prettier --check "src/**/*.{ts,tsx}"

workflows:
  version: 2
  test:
    jobs:
      - clippy
      - rustfmt
      - test-nightly
      - test-stable

      - prettier
      - test-react
